### ISSUE TITLE
ImportError: No module named serial

### ISSUE THREAD

**Issue by bgilreath** [RoverRobotics/rr_openrover_stack#41]
Error when RPi 3B+ controlling Rover Zero. Seems to be missing python package?

Ubuntu 18.04 server 32-bit

`roslaunch rr_rover_zero_driver example.launch
... logging to /home/ubuntu/.ros/log/95af51ac-6e4e-11ea-a03f-b827eb2b8561/roslaunch-ubuntu-10424.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:36967/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.5
 * /rover_zero_driver_node/attempts: 1
 * /rover_zero_driver_node/baud: 115200
 * /rover_zero_driver_node/dev: /dev/ttyACM0
 * /rover_zero_driver_node/diag_frequency: 1.0
 * /rover_zero_driver_node/effort_coef: 0.09
 * /rover_zero_driver_node/max_turn: 6.28
 * /rover_zero_driver_node/max_vel: 5.0
 * /rover_zero_driver_node/timeout: 0.1

NODES
  /
    rover_zero_driver_node (rr_rover_zero_driver/rover_zero.py)

auto-starting new master
process[master]: started with pid [10434]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 95af51ac-6e4e-11ea-a03f-b827eb2b8561
process[rosout-1]: started with pid [10445]
started core service [/rosout]
process[rover_zero_driver_node-2]: started with pid [10448]
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/scripts/rover_zero.py", line 2, in <module>
    from roboclaw_driver.roboclaw import Roboclaw
  File "/home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/driver/roboclaw_driver/roboclaw.py", line 2, in <module>
    import serial
ImportError: No module named serial
[rover_zero_driver_node-2] process has died [pid 10448, exit code 1, cmd /home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/scripts/rover_zero.py __name:=rover_zero_driver_node __log:=/home/ubuntu/.ros/log/95af51ac-6e4e-11ea-a03f-b827eb2b8561/rover_zero_driver_node-2.log].
log file: /home/ubuntu/.ros/log/95af51ac-6e4e-11ea-a03f-b827eb2b8561/rover_zero_driver_node-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by bgilreath** [comment]
Installing python-serial solved problem.
`sudo apt install python-serial`
