### ISSUE TITLE
AttributeError: RoverZeroNode instance has no attribute '_odom_frame'

### ISSUE THREAD

**Issue by bgilreath** [RoverRobotics/rr_openrover_stack#99]
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/scripts/rover_zero.py", line 449, in <module>
    rz = RoverZeroNode()
  File "/home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/scripts/rover_zero.py", line 57, in __init__
    self.verify_ros_parameters()
  File "/home/ubuntu/catkin_ws/src/rr_openrover_stack/rr_rover_zero_driver/scripts/rover_zero.py", line 223, in verify_ros_parameters
    if not isinstance(self._odom_frame, str) or not self._odom_frame:
AttributeError: RoverZeroNode instance has no attribute '_odom_frame'

**Comment by jbrover** [comment]
Hello, as a sanity check could you please verify that your launch file has a non-zero, positive value for 'odom_frequency_hz' ?

ie something like:
param name="odom_frequency_hz" value="30.0"

**Comment by bgilreath** [comment]
![image](https://user-images.githubusercontent.com/9235/100677076-18529480-331f-11eb-9b55-a71b6001af83.jpeg)

**Comment by bgilreath** [comment]
There may be indention issue in lines above line reported to be failing.

**Comment by jbrover** [comment]
Thanks for checking the launch file. Can you be more specific on what you think is the indentation issue?

I've reviewed rover_zero.py and believe the following to be true:

- self._odom_frame attribute is created on line 105 if the odom_frequency_hz is non-zero and positive.
-The self.verify_ros_parameters() checks self._odom_frame before self._odom_frame is created.

This appears to be a bug. I can create a branch with some minor changes to determine if this is a solution to the exception you are seeing.

**Comment by jbrover** [comment]
I have created a branch called odom_frame_test and I have moved the verify parameters routine to after the _odom_frame attribute is created. Please test this and let me know what you find.

**Comment by jbrover** [comment]
I should add that we've recreated the error that you are seeing on the melodic-devel branch and have verified that the error is resolved on the branch we just created called odom_frame_test.

**Comment by bgilreath** [comment]
Do you still want me to test, or are you just going to integrate the bug fix into the melodic-devel branch?

**Comment by jbrover** [comment]
Yes we would like confirmation from you that are no longer seeing issues.

**Comment by bgilreath** [comment]
Confirmed. No longer an issue by using odom_test_frame.
